### ISSUE TITLE
How to modify code to make it work on our image data?

### ISSUE THREAD

**Issue by sainimohit23** [ngthanhtin/Line_Segmentation#1]

**Comment by ngthanhtin** [comment]
Hi, you just need to point out the input image directory and create a result folder.

**Comment by raghav-menon** [comment]
Hi, 
 Tried using the code for line segmentation. It seem to work for your image but when I provide new images, it is failing. Am I missing anything here? Is there anything else that needs to be done apart from pointing to the correct image directory and creating a result folder. Any help would be appreciated!!

**Comment by ngthanhtin** [comment]
Could you provide some of your image ?

**Comment by raghav-menon** [comment]
Thank you for the quick reply. The images were taken from 

https://github.com/Samir55/Image2Lines/tree/master/img

It gives me only one line i.e. the first line.

**Comment by ngthanhtin** [comment]
Maybe you should tune the parameters when thresholding the image.

**Comment by raghav-menon** [comment]
The image is taken from the CPP version of the program and I see that in the thresholding and smoothing part the kernals you have used and they have used are the same.

**Comment by imsunnykr** [comment]
> Thank you for the quick reply. The images were taken from
> 
> https://github.com/Samir55/Image2Lines/tree/master/img
> 
> It gives me only one line i.e. the first line.

I am facing the same issue. Just getting the first line. Did you find any solution?

**Comment by espetro** [comment]
Hi! The python version is working 🤠 I've made a few modifications to work with opencv/numpy array-like images. You can find the code [here](https://github.com/espetro/text-processing/blob/master/preproc/line.py) for LineSegmentation and [here](https://github.com/espetro/text-processing/blob/master/preproc/line_utils.py) for the other classes.

It should go at least 5x faster than the current Python implementation due to Numba 😄
